/* Script generated by Pawn Studio */

#include <amxmodx>
#include <fun>
#include <cstrike>
#include <zp43_armas>

new g_item;

public plugin_init()
{
	register_plugin("Weapon", "0.1", "Hypnotize")
	// Add your own code here
	g_item = zp_arma("Famas", 2, 0, PRIMARIA, ADMIN_ALL, "");
}

public dar_arma(id, item)
{
	if( g_item != item )
		return;

	give_item(id, "weapon_famas");
	cs_set_user_bpammo(id, CSW_FAMAS, 99);
	return;
}	