/* Script generated by Pawn Studio */

#include <amxmodx>
#include <reapi>
#include <zp43_armas>

new g_item;

public plugin_init()
{
	register_plugin("Weapon", "0.1", "Hypnotize")
	// Add your own code here
	g_item = zp_arma("Seal-Knife", 0, 0, KNIFE, ADMIN_ALL, "");
}

public dar_arma(id, item)
{
	if( g_item != item )
		return;

	rg_give_item(id, "weapon_knife");
	return;
}	